import { PortfolioData, UserAccount } from '../types/portfolio';

export const createInitialPortfolio = (user?: UserAccount | null): PortfolioData => {
  const userName = user?.name?.trim() || '';
  const userEmail = user?.email?.trim() || '';
  const title = userName ? `${userName}'s Portfolio` : 'My Professional Portfolio';
  const slug = userName
    ? userName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
    : `portfolio-${Math.floor(1000 + Math.random() * 9000)}`;

  return {
    id: `port-${Date.now()}`,
    userId: user?.id || 'user-local',
    title,
    slug,
    updatedAt: new Date().toISOString(),
    targetRole: 'fullstack',
    language: 'en',
    theme: {
      templateId: 'modern-dev',
      colorTheme: 'indigo',
      fontFamily: 'plus-jakarta',
      darkMode: true,
      borderRadius: 'md',
      backgroundStyle: 'mesh',
    },
    sectionsOrder: [
      'profile',
      'about',
      'experience',
      'projects',
      'skills',
      'internships',
      'education',
      'codingProfiles',
      'certifications',
      'achievements',
      'blogs',
      'testimonials',
      'socialLinks',
      'hobbies',
      'contact',
    ],
    enabledSections: {
      profile: true,
      about: true,
      experience: true,
      internships: false,
      projects: true,
      skills: true,
      education: true,
      certifications: false,
      achievements: false,
      codingProfiles: true,
      socialLinks: true,
      blogs: false,
      testimonials: false,
      hobbies: false,
      contact: true,
    },
    profile: {
      fullName: userName,
      title: user?.role || '',
      tagline: '',
      headline: '',
      avatarUrl: user?.avatar || '',
      coverImageUrl: '',
      email: userEmail,
      phone: '',
      location: '',
      availabilityBadge: 'open_to_work',
      resumeUrl: '',
      primaryActionText: 'View Projects',
      secondaryActionText: 'Contact Me',
    },
    about: {
      summary: '',
      careerObjective: '',
      yearsOfExperience: '',
      completedProjectsCount: '',
      satisfiedClientsCount: '',
      coffeeCount: '',
      highlights: [],
    },
    experience: [],
    internships: [],
    projects: [],
    skills: [],
    education: [],
    certifications: [],
    achievements: [],
    codingProfiles: {
      github: '',
      leetcode: '',
      codeforces: '',
      hackerrank: '',
      kaggle: '',
      devpost: '',
      stackoverflow: '',
    },
    socialLinks: {
      linkedin: '',
      twitter: '',
      medium: '',
      website: '',
      dribbble: '',
      discord: '',
    },
    blogs: [],
    testimonials: [],
    hobbies: [],
    contact: {
      email: userEmail,
      phone: '',
      location: '',
      calendlyUrl: '',
      customMessage: '',
      enableDirectForm: true,
    },
    customSections: [],
  };
};
