import { LanguageCode } from '../types/portfolio';

export interface TranslationDictionary {
  appName: string;
  tagline: string;
  dashboard: string;
  builder: string;
  preview: string;
  exportShare: string;
  aiAssistant: string;
  aiAnalysis: string;
  resumeImport: string;
  githubSync: string;
  templates: string;
  themes: string;
  sections: string;
  saveChanges: string;
  autoSaved: string;
  viewLive: string;
  qrCode: string;
  copyLink: string;
  linkCopied: string;
  downloadPdf: string;
  targetRole: string;
  completeness: string;
  recruiterScore: string;
  missingSections: string;
  addSection: string;
  deleteItem: string;
  editItem: string;
  profile: string;
  aboutMe: string;
  experience: string;
  internships: string;
  projects: string;
  skills: string;
  education: string;
  certifications: string;
  achievements: string;
  codingProfiles: string;
  socialLinks: string;
  blogs: string;
  testimonials: string;
  hobbies: string;
  contact: string;
  viewProject: string;
  sourceCode: string;
  contactMe: string;
  openToWork: string;
  freelancing: string;
  employed: string;
  seekingInternship: string;
  allCategories: string;
  filterBy: string;
  featuredProjects: string;
  allProjects: string;
  sendEmail: string;
  name: string;
  email: string;
  message: string;
  sendMessage: string;
  messageSent: string;
}

export const TRANSLATIONS: Record<LanguageCode, TranslationDictionary> = {
  en: {
    appName: 'FolioCraft AI',
    tagline: 'AI-Powered Developer & Tech Portfolio Studio',
    dashboard: 'Dashboard',
    builder: 'Builder',
    preview: 'Live Preview',
    exportShare: 'Share & Export',
    aiAssistant: 'AI Copilot',
    aiAnalysis: 'AI Analysis',
    resumeImport: 'Resume Import',
    githubSync: 'GitHub Sync',
    templates: 'Templates',
    themes: 'Theme & Style',
    sections: 'Sections',
    saveChanges: 'Save Changes',
    autoSaved: 'Auto-saved to Cloud',
    viewLive: 'Live Site',
    qrCode: 'QR Code',
    copyLink: 'Copy URL',
    linkCopied: 'Copied to clipboard!',
    downloadPdf: 'Download PDF',
    targetRole: 'Target Role',
    completeness: 'Completeness',
    recruiterScore: 'Recruiter Score',
    missingSections: 'Missing Sections',
    addSection: 'Add Item',
    deleteItem: 'Delete',
    editItem: 'Edit',
    profile: 'Profile & Hero',
    aboutMe: 'About Me',
    experience: 'Work Experience',
    internships: 'Internships',
    projects: 'Featured Projects',
    skills: 'Skills & Tech Stack',
    education: 'Education',
    certifications: 'Certifications',
    achievements: 'Achievements & Awards',
    codingProfiles: 'Coding Profiles',
    socialLinks: 'Social Links',
    blogs: 'Articles & Blogs',
    testimonials: 'Testimonials',
    hobbies: 'Interests & Hobbies',
    contact: 'Contact & Connect',
    viewProject: 'Live Demo',
    sourceCode: 'Source Code',
    contactMe: 'Get In Touch',
    openToWork: 'Available for Hire',
    freelancing: 'Open for Freelance',
    employed: 'Currently Employed',
    seekingInternship: 'Seeking Internship',
    allCategories: 'All Categories',
    filterBy: 'Filter by',
    featuredProjects: 'Featured Projects',
    allProjects: 'All Projects',
    sendEmail: 'Send Email',
    name: 'Your Name',
    email: 'Your Email',
    message: 'Your Message',
    sendMessage: 'Send Message',
    messageSent: 'Thank you! Message sent successfully.',
  },
  es: {
    appName: 'FolioCraft AI',
    tagline: 'Estudio de Portafolios con Inteligencia Artificial',
    dashboard: 'Panel',
    builder: 'Constructor',
    preview: 'Vista Previa',
    exportShare: 'Compartir y Exportar',
    aiAssistant: 'Asistente IA',
    aiAnalysis: 'Análisis IA',
    resumeImport: 'Importar CV',
    githubSync: 'Sincronizar GitHub',
    templates: 'Plantillas',
    themes: 'Tema y Estilo',
    sections: 'Secciones',
    saveChanges: 'Guardar Cambios',
    autoSaved: 'Guardado automático',
    viewLive: 'Ver Sitio',
    qrCode: 'Código QR',
    copyLink: 'Copiar Enlace',
    linkCopied: '¡Copiado al portapapeles!',
    downloadPdf: 'Descargar PDF',
    targetRole: 'Rol Objetivo',
    completeness: 'Completitud',
    recruiterScore: 'Puntuación Reclutador',
    missingSections: 'Secciones Faltantes',
    addSection: 'Añadir Elemento',
    deleteItem: 'Eliminar',
    editItem: 'Editar',
    profile: 'Perfil y Portada',
    aboutMe: 'Sobre Mí',
    experience: 'Experiencia Laboral',
    internships: 'Pasantías',
    projects: 'Proyectos Destacados',
    skills: 'Habilidades Técnicas',
    education: 'Educación',
    certifications: 'Certificaciones',
    achievements: 'Logros y Premios',
    codingProfiles: 'Perfiles de Programación',
    socialLinks: 'Redes Sociales',
    blogs: 'Artículos y Blog',
    testimonials: 'Testimonios',
    hobbies: 'Intereses y Hobbies',
    contact: 'Contacto',
    viewProject: 'Demo en Vivo',
    sourceCode: 'Código Fuente',
    contactMe: 'Contáctame',
    openToWork: 'Disponible para Contratación',
    freelancing: 'Disponible Freelance',
    employed: 'Empleado Actualmente',
    seekingInternship: 'Buscando Pasantía',
    allCategories: 'Todas las Categorías',
    filterBy: 'Filtrar por',
    featuredProjects: 'Proyectos Destacados',
    allProjects: 'Todos los Proyectos',
    sendEmail: 'Enviar Correo',
    name: 'Tu Nombre',
    email: 'Tu Correo',
    message: 'Tu Mensaje',
    sendMessage: 'Enviar Mensaje',
    messageSent: '¡Gracias! Mensaje enviado con éxito.',
  },
  fr: {
    appName: 'FolioCraft AI',
    tagline: 'Créateur de Portfolio Intelligent pour Développeurs',
    dashboard: 'Tableau de bord',
    builder: 'Constructeur',
    preview: 'Aperçu Direct',
    exportShare: 'Partager & Exporter',
    aiAssistant: 'Copilote IA',
    aiAnalysis: 'Analyse IA',
    resumeImport: 'Importer CV',
    githubSync: 'Synchro GitHub',
    templates: 'Modèles',
    themes: 'Thèmes & Style',
    sections: 'Sections',
    saveChanges: 'Enregistrer',
    autoSaved: 'Sauvegarde auto',
    viewLive: 'Site en Ligne',
    qrCode: 'Code QR',
    copyLink: 'Copier le lien',
    linkCopied: 'Copié dans le presse-papier !',
    downloadPdf: 'Télécharger PDF',
    targetRole: 'Rôle Visé',
    completeness: 'Complétude',
    recruiterScore: 'Score Recruteur',
    missingSections: 'Sections Manquantes',
    addSection: 'Ajouter',
    deleteItem: 'Supprimer',
    editItem: 'Modifier',
    profile: 'Profil & Accueil',
    aboutMe: 'À Propos',
    experience: 'Expérience Professionnelle',
    internships: 'Stages',
    projects: 'Projets Réalisés',
    skills: 'Compétences',
    education: 'Formation',
    certifications: 'Certifications',
    achievements: 'Distinctions & Prix',
    codingProfiles: 'Profils Code',
    socialLinks: 'Réseaux Sociaux',
    blogs: 'Articles & Publications',
    testimonials: 'Recommandations',
    hobbies: 'Centres d\'intérêt',
    contact: 'Contact',
    viewProject: 'Démo Live',
    sourceCode: 'Code Source',
    contactMe: 'Me Contacter',
    openToWork: 'À l\'écoute d\'opportunités',
    freelancing: 'Disponible Freelance',
    employed: 'En Poste',
    seekingInternship: 'Recherche de Stage',
    allCategories: 'Toutes Catégories',
    filterBy: 'Filtrer par',
    featuredProjects: 'Projets Phares',
    allProjects: 'Tous les Projets',
    sendEmail: 'Envoyer un Email',
    name: 'Votre Nom',
    email: 'Votre Email',
    message: 'Votre Message',
    sendMessage: 'Envoyer',
    messageSent: 'Merci ! Votre message a été envoyé.',
  },
  de: {
    appName: 'FolioCraft AI',
    tagline: 'KI-gestützter Entwickler-Portfolio-Baukasten',
    dashboard: 'Übersicht',
    builder: 'Editor',
    preview: 'Live-Vorschau',
    exportShare: 'Teilen & Exportieren',
    aiAssistant: 'KI-Assistent',
    aiAnalysis: 'KI-Analyse',
    resumeImport: 'Lebenslauf importieren',
    githubSync: 'GitHub Sync',
    templates: 'Vorlagen',
    themes: 'Farben & Design',
    sections: 'Bereiche',
    saveChanges: 'Speichern',
    autoSaved: 'Automatisch gespeichert',
    viewLive: 'Live-Ansicht',
    qrCode: 'QR-Code',
    copyLink: 'Link kopieren',
    linkCopied: 'In Zwischenablage kopiert!',
    downloadPdf: 'PDF herunterladen',
    targetRole: 'Zielposition',
    completeness: 'Vollständigkeit',
    recruiterScore: 'Recruiter-Score',
    missingSections: 'Fehlende Abschnitte',
    addSection: 'Eintrag hinzufügen',
    deleteItem: 'Löschen',
    editItem: 'Bearbeiten',
    profile: 'Profil & Header',
    aboutMe: 'Über mich',
    experience: 'Berufserfahrung',
    internships: 'Praktika',
    projects: 'Ausgewählte Projekte',
    skills: 'Kenntnisse & Tech-Stack',
    education: 'Ausbildung',
    certifications: 'Zertifikate',
    achievements: 'Auszeichnungen',
    codingProfiles: 'Coding-Profile',
    socialLinks: 'Soziale Netzwerke',
    blogs: 'Artikel & Blog',
    testimonials: 'Empfehlungen',
    hobbies: 'Interessen & Hobbys',
    contact: 'Kontakt',
    viewProject: 'Live-Demo',
    sourceCode: 'Quellcode',
    contactMe: 'Kontaktieren',
    openToWork: 'Verfügbar für Angebote',
    freelancing: 'Offen für Freelance',
    employed: 'In Festanstellung',
    seekingInternship: 'Praktikumsplatz gesucht',
    allCategories: 'Alle Kategorien',
    filterBy: 'Filtern nach',
    featuredProjects: 'Top-Projekte',
    allProjects: 'Alle Projekte',
    sendEmail: 'E-Mail senden',
    name: 'Name',
    email: 'E-Mail',
    message: 'Nachricht',
    sendMessage: 'Nachricht senden',
    messageSent: 'Vielen Dank! Nachricht wurde gesendet.',
  },
  hi: {
    appName: 'FolioCraft AI',
    tagline: 'एआई-संचालित पेशेवर पोर्टफोलियो निर्माता',
    dashboard: 'डैशबोर्ड',
    builder: 'बिल्डर',
    preview: 'लाइव पूर्वावलोकन',
    exportShare: 'शेयर और निर्यात',
    aiAssistant: 'एआई सहायक',
    aiAnalysis: 'एआई विश्लेषण',
    resumeImport: 'बायोडाटा आयात',
    githubSync: 'गिटहब सिंक',
    templates: 'टेम्पलेट्स',
    themes: 'थीम और शैली',
    sections: 'अनुभाग',
    saveChanges: 'परिवर्तन सहेजें',
    autoSaved: 'स्वतः सहेजा गया',
    viewLive: 'लाइव देखें',
    qrCode: 'क्यूआर कोड',
    copyLink: 'लिंक कॉपी करें',
    linkCopied: 'क्लिपबोर्ड पर कॉपी किया गया!',
    downloadPdf: 'पीडीएफ डाउनलोड करें',
    targetRole: 'लक्ष्य भूमिका',
    completeness: 'पूर्णता',
    recruiterScore: 'रिक्रूटर स्कोर',
    missingSections: 'गायब अनुभाग',
    addSection: 'जोड़ें',
    deleteItem: 'हटाएं',
    editItem: 'संपादित करें',
    profile: 'प्रोफ़ाइल और परिचय',
    aboutMe: 'मेरे बारे में',
    experience: 'कार्य अनुभव',
    internships: 'इंटर्नशिप',
    projects: 'प्रमुख परियोजनाएं',
    skills: 'कौशल और तकनीक',
    education: 'शिक्षा',
    certifications: 'प्रमाणपत्र',
    achievements: 'उपलब्धियां और पुरस्कार',
    codingProfiles: 'कोडिंग प्रोफाइल',
    socialLinks: 'सोशल लिंक',
    blogs: 'ब्लॉग और लेख',
    testimonials: 'प्रशंसापत्र',
    hobbies: 'शौक और रुचियां',
    contact: 'संपर्क करें',
    viewProject: 'लाइव डेमो',
    sourceCode: 'स्रोत कोड',
    contactMe: 'संपर्क करें',
    openToWork: 'नौकरी के लिए उपलब्ध',
    freelancing: 'फ्रीलांस उपलब्ध',
    employed: 'वर्तमान में कार्यरत',
    seekingInternship: 'इंटर्नशिप की तलाश',
    allCategories: 'सभी श्रेणियां',
    filterBy: 'फ़िल्टर करें',
    featuredProjects: 'विशेष परियोजनाएं',
    allProjects: 'सभी परियोजनाएं',
    sendEmail: 'ईमेल भेजें',
    name: 'आपका नाम',
    email: 'आपका ईमेल',
    message: 'संदेश',
    sendMessage: 'संदेश भेजें',
    messageSent: 'धन्यवाद! संदेश सफलतापूर्वक भेजा गया।',
  },
  ja: {
    appName: 'FolioCraft AI',
    tagline: 'AI搭載エンジニア向けポートフォリオスタジオ',
    dashboard: 'ダッシュボード',
    builder: 'ビルダー',
    preview: 'プレビュー',
    exportShare: '共有・エクスポート',
    aiAssistant: 'AIアシスタント',
    aiAnalysis: 'AI分析',
    resumeImport: '履歴書インポート',
    githubSync: 'GitHub同期',
    templates: 'テンプレート',
    themes: 'テーマ・スタイル',
    sections: 'セクション',
    saveChanges: '保存',
    autoSaved: '自動保存済み',
    viewLive: 'サイトを見る',
    qrCode: 'QRコード',
    copyLink: 'リンクをコピー',
    linkCopied: 'クリップボードにコピーしました！',
    downloadPdf: 'PDFダウンロード',
    targetRole: '目標職種',
    completeness: '完成度',
    recruiterScore: '採用スコア',
    missingSections: '未入力セクション',
    addSection: '項目を追加',
    deleteItem: '削除',
    editItem: '編集',
    profile: 'プロフィール',
    aboutMe: '自己紹介',
    experience: '職務経歴',
    internships: 'インターンシップ',
    projects: '実績プロジェクト',
    skills: 'スキル・技術',
    education: '学歴',
    certifications: '資格・認定',
    achievements: '受賞歴・実績',
    codingProfiles: 'コーディングプロファイル',
    socialLinks: 'SNSリンク',
    blogs: '記事・ブログ',
    testimonials: '推薦・評価',
    hobbies: '趣味・関心',
    contact: 'お問い合わせ',
    viewProject: 'デモを見る',
    sourceCode: 'ソースコード',
    contactMe: '連絡する',
    openToWork: '転職活動中',
    freelancing: 'フリーランス募集中',
    employed: '現職中',
    seekingInternship: 'インターン希望',
    allCategories: 'すべてのカテゴリ',
    filterBy: '絞り込み',
    featuredProjects: '注目プロジェクト',
    allProjects: 'すべてのプロジェクト',
    sendEmail: 'メールを送信',
    name: 'お名前',
    email: 'メールアドレス',
    message: 'メッセージ',
    sendMessage: '送信する',
    messageSent: 'ありがとうございます！送信が完了しました。',
  },
  pt: {
    appName: 'FolioCraft AI',
    tagline: 'Criador de Portfólios com Inteligência Artificial',
    dashboard: 'Painel',
    builder: 'Construtor',
    preview: 'Pré-visualização',
    exportShare: 'Compartilhar & Exportar',
    aiAssistant: 'Assistente IA',
    aiAnalysis: 'Análise IA',
    resumeImport: 'Importar Currículo',
    githubSync: 'Sincronizar GitHub',
    templates: 'Modelos',
    themes: 'Tema & Estilo',
    sections: 'Seções',
    saveChanges: 'Salvar',
    autoSaved: 'Salvo automaticamente',
    viewLive: 'Ver Site',
    qrCode: 'Código QR',
    copyLink: 'Copiar Link',
    linkCopied: 'Copiado para a área de transferência!',
    downloadPdf: 'Baixar PDF',
    targetRole: 'Cargo Desejado',
    completeness: 'Completude',
    recruiterScore: 'Pontuação do Recrutador',
    missingSections: 'Seções Ausentes',
    addSection: 'Adicionar',
    deleteItem: 'Excluir',
    editItem: 'Editar',
    profile: 'Perfil & Início',
    aboutMe: 'Sobre Mim',
    experience: 'Experiência Profissional',
    internships: 'Estágios',
    projects: 'Projetos em Destaque',
    skills: 'Habilidades & Tecnologias',
    education: 'Formação Acadêmica',
    certifications: 'Certificações',
    achievements: 'Conquistas & Prêmios',
    codingProfiles: 'Perfis de Código',
    socialLinks: 'Redes Sociais',
    blogs: 'Artigos & Blog',
    testimonials: 'Depoimentos',
    hobbies: 'Interesses & Hobbies',
    contact: 'Contato',
    viewProject: 'Ver Demo',
    sourceCode: 'Código Fonte',
    contactMe: 'Entrar em Contato',
    openToWork: 'Disponível para Trabalho',
    freelancing: 'Disponível para Freelance',
    employed: 'Empregado Atualmente',
    seekingInternship: 'Buscando Estágio',
    allCategories: 'Todas as Categorias',
    filterBy: 'Filtrar por',
    featuredProjects: 'Projetos em Destaque',
    allProjects: 'Todos os Projetos',
    sendEmail: 'Enviar E-mail',
    name: 'Seu Nome',
    email: 'Seu E-mail',
    message: 'Sua Mensagem',
    sendMessage: 'Enviar Mensagem',
    messageSent: 'Obrigado! Mensagem enviada com sucesso.',
  },
  zh: {
    appName: 'FolioCraft AI',
    tagline: 'AI 驱动的高级开发者与求职者作品集生成器',
    dashboard: '控制台',
    builder: '编辑器',
    preview: '实时预览',
    exportShare: '分享与导出',
    aiAssistant: 'AI 助手',
    aiAnalysis: 'AI 深度分析',
    resumeImport: '简历导入',
    githubSync: 'GitHub 同步',
    templates: '精选模板',
    themes: '主题与风格',
    sections: '模块管理',
    saveChanges: '保存更改',
    autoSaved: '已自动保存',
    viewLive: '浏览网页',
    qrCode: '二维码',
    copyLink: '复制链接',
    linkCopied: '已复制到剪贴板！',
    downloadPdf: '导出 PDF',
    targetRole: '目标岗位',
    completeness: '完整度',
    recruiterScore: '招聘官评分',
    missingSections: '待完善模块',
    addSection: '添加项目',
    deleteItem: '删除',
    editItem: '编辑',
    profile: '个人简介与头图',
    aboutMe: '关于我',
    experience: '工作经历',
    internships: '实习经历',
    projects: '精选项目',
    skills: '专业技能',
    education: '教育背景',
    certifications: '专业证书',
    achievements: '荣誉与成就',
    codingProfiles: '代码主页',
    socialLinks: '社交链接',
    blogs: '精选文章',
    testimonials: '推荐评价',
    hobbies: '兴趣爱好',
    contact: '联系方式',
    viewProject: '查看演示',
    sourceCode: '源码仓库',
    contactMe: '立即联系',
    openToWork: '随时到岗 / 寻找机会',
    freelancing: '承接自由职业',
    employed: '在职状态',
    seekingInternship: '寻找实习',
    allCategories: '全部分类',
    filterBy: '筛选',
    featuredProjects: '精选项目',
    allProjects: '全部项目',
    sendEmail: '发送邮件',
    name: '姓名',
    email: '电子邮箱',
    message: '留言内容',
    sendMessage: '发送留言',
    messageSent: '谢谢！您的留言已成功送达。',
  },
};
